server:
  port: 8089

dubbo:
  application:
    name: coder-resolver-consumer
    qos-accept-foreign-ip: true
    qos-port: 22225
  protocol:
    name: dubbo
    port: 20885
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  metrics:
    enable-jvm: true

#开启包扫描，可替代 @EnableDubbo 注解
##dubbo.scan.base-packages=com.zang.gmall