server:
    port: 8084
dubbo:
  provider:
    prefer-serialization: fastjson2,hessian2
  application:
    logger: slf4j
    name: code-resolver-consumer
    qos-accept-foreign-ip: true
    qos-port: 22226
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
      name: dubbo
      payload: 2010241024
      port: -1
  metrics:
      enable-jvm: true
spring:
  mvc:
    pathmatch:
      #?????swagger Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
      #??Springfox??????????AntPathMatcher???Spring Boot 2.6.X????PathPatternMatcher
      matching-strategy: ant_path_matcher
  data:
    neo4j:
      database: mvc
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      password: 123456
  neo4j:
    authentication:
      username: neo4j
      password: 12345678
    uri: bolt://127.0.0.1:7687
  thymeleaf:
    cache: false
  servlet: #上传文件大小限制
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/joern/**' #默认扫描全部的接口
      packages-to-scan: com.icbc.codeResolver.controller  #不加会默认扫描全部的包

#下面是upload的文件位置配置
file:
  upload:
    dir: E:/University/GHLearning/uploadSave
    disableTypes: dll,exe
#下面是parse的文件配置【不需要在这里写】
#joern:
#  dir: E:\\software\\Joern\\joern
#import:
#  dir: E:\\software\\neo4j\\Data\\relate-data\\dbmss\\dbms-dc752007-1b88-4751-adae-6f161a7539d7\\import
#source:
#  dir: E:\\software\\Joern\\joern\\out\\*
#import_to_db:
#  dir: E:\\software\\neo4j\\Data\\relate-data\\dbmss\\dbms-dc752007-1b88-4751-adae-6f161a7539d7
#node_csv: E:\\software\\neo4j\\Data\\relate-data\\dbmss\\dbms-dc752007-1b88-4751-adae-6f161a7539d7\\import\\nodes_*_cypher.csv
#edge_csv: E:\\software\\neo4j\\Data\\relate-data\\dbmss\\dbms-dc752007-1b88-4751-adae-6f161a7539d7\\import\\edges_*_cypher.csv
#cpg:
#  dir: E:/University/GHLearning/parseSave/cpg.bin
#database: test
