server:
  port: 8082

spring:
  data:
    neo4j:
      database: neo4j
  neo4j:
    authentication:
      username: neo4j
      password: chenqiujian123
    uri: bolt://127.0.0.1:7687

dubbo:
  application:
    name: tabby-service-provider
    qos-port: 22224
    qos-accept-foreign-ip: true
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882
  monitor:
    protocol: registry
  metrics:
    enable-jvm: true


#开启包扫描，可替代 @EnableDubbo 注解
##dubbo.scan.base-packages=com.zang.gmall