server:
  port: 8081
dubbo:
  application:
    name: joern-service-provider
    qos-accept-foreign-ip: true
    qos-port: 22223
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  metrics:
    enable-jvm: true
#  monitor:
#    protocol: registry
spring:
  application:
    name: spring-neo4j
  mvc:
    pathmatch:
      #解决异常：swagger Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
      #因为Springfox使用的路径匹配是基于AntPathMatcher的，而Spring Boot 2.6.X使用的是PathPatternMatcher
      matching-strategy: ant_path_matcher
  data:
    neo4j:
      database: resolvertest
    redis:
      host: localhost
      port: 6379
      database: 1
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
  neo4j:
    authentication:
      username: neo4j
      password: chenqiujian123
    uri: bolt://127.0.0.1:7687
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/joern/**' #默认扫描全部的接口
      packages-to-scan: com.icbc.codeResolver.controller  #不加会默认扫描全部的包

#开启包扫描，可替代 @EnableDubbo 注解
##dubbo.scan.base-packages=com.zang.gmall